// Turns src/lib/data/ported-listings.ts into a SQL seed file that inserts
// every ported product into a real Supabase project.
//
// Usage:  npx tsx scripts/generate-seed-sql.ts > supabase/seed.sql
// Then either paste supabase/seed.sql into the Supabase SQL editor, or run
// it with the Supabase CLI (`supabase db execute -f supabase/seed.sql`)
// after applying supabase/migrations/0001_init.sql.
//
// Images are intentionally left empty (see the note at the top of
// ported-listings.ts) — add rows to product_images once real photos are
// uploaded through the admin panel or Supabase storage.

import { portedProducts } from "../src/lib/data/ported-listings";

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

const lines: string[] = [
  "-- Auto-generated by scripts/generate-seed-sql.ts — do not hand-edit.",
  "-- Ports the live embellishantiques.com catalog (names/prices/categories only; see",
  "-- src/lib/data/ported-listings.ts for what's still placeholder).",
  "",
];

for (const p of portedProducts) {
  lines.push(
    `insert into products (slug, name, description, price_cents, category, status, is_new_arrival) values (` +
      `'${sqlEscape(p.slug)}', '${sqlEscape(p.name)}', '${sqlEscape(p.description)}', ${p.priceCents}, ` +
      `'${sqlEscape(p.category)}', 'available', false) on conflict (slug) do nothing;`
  );
}

process.stdout.write(lines.join("\n") + "\n");
